server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/auth/**
          filters:
            - StripPrefix=0

        # Post Service Routes (with /studify prefix)
        - id: post-service-studify
          uri: lb://post-service
          predicates:
            - Path=/studify/api/v1/post/**
          filters:
            - RewritePath=/studify/(?<segment>.*), /$\{segment}
            
        # Post Service Routes  
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**, /api/v1/post/**
          filters:
            - StripPrefix=0

        # Notification Service Routes
        - id: notification-service  
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: "change-me-please-very-long-secret-key-for-dev"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG